#37 issue - zabezpieczenie przed brakiem połączenia z internetem
envirosolutionspl/uldk pull request #43
Opened 2024-05-07 13:59 UTC by agluszek

2024-05-07 19:33 UTC, wojtek19022 requested changes
Generalnie fajnie działa to, ale dopiero jak ktoś uruchomił już wcześniej wtyczkę i nagle mu przerwało łącze. Jak nie mam włączonego internetu podczas startu QGIS, to niestety nie mogę otrzymać województw itd. nawet jak włączę internet przy drugim odpaleniu okienka wtyczki. Dopiero jak zrestartuję QGIS i uruchomię go z internetem, to wtedy mi się sczytują wszystkie wartości prawidłowo

Proponuję ściągnąć funkcje odpowiadające za sczytanie tych atrybutów z pliku [uldk_gugik_dialog.py](https://github.com/envirosolutionspl/uldk/blob/master/uldk_gugik_dialog.py) i zmusić wtyczkę przy inicjalizacji okna wtyczki do wykonania tych funkcji. Ewentualnie przenieść te funkcje z dialogu do innego skryptu, zostawiam do pokminienia, w każdym razie musi też być uodpornienei na to co pisałem w pierwszej części

2024-05-10 12:39 UTC, agluszek commented
> Generalnie fajnie działa to, ale dopiero jak ktoś uruchomił już wcześniej wtyczkę i nagle mu przerwało łącze. Jak nie mam włączonego internetu podczas startu QGIS, to niestety nie mogę otrzymać województw itd. nawet jak włączę internet przy drugim odpaleniu okienka wtyczki. Dopiero jak zrestartuję QGIS i uruchomię go z internetem, to wtedy mi się sczytują wszystkie wartości prawidłowo
> 
> Proponuję ściągnąć funkcje odpowiadające za sczytanie tych atrybutów z pliku [uldk_gugik_dialog.py](https://github.com/envirosolutionspl/uldk/blob/master/uldk_gugik_dialog.py) i zmusić wtyczkę przy inicjalizacji okna wtyczki do wykonania tych funkcji. Ewentualnie przenieść te funkcje z dialogu do innego skryptu, zostawiam do pokminienia, w każdym razie musi też być uodpornienei na to co pisałem w pierwszej części

zmieniłam kolejność wypełniania dialogu - robi się to w funkcji _run_ zamiast przy inicjalizacji
btw jakbyś mergował to proszę zesquoshuj commity

2024-05-11 08:36 UTC, wojtek19022 commented
> > Generalnie fajnie działa to, ale dopiero jak ktoś uruchomił już wcześniej wtyczkę i nagle mu przerwało łącze. Jak nie mam włączonego internetu podczas startu QGIS, to niestety nie mogę otrzymać województw itd. nawet jak włączę internet przy drugim odpaleniu okienka wtyczki. Dopiero jak zrestartuję QGIS i uruchomię go z internetem, to wtedy mi się sczytują wszystkie wartości prawidłowo
> > Proponuję ściągnąć funkcje odpowiadające za sczytanie tych atrybutów z pliku [uldk_gugik_dialog.py](https://github.com/envirosolutionspl/uldk/blob/master/uldk_gugik_dialog.py) i zmusić wtyczkę przy inicjalizacji okna wtyczki do wykonania tych funkcji. Ewentualnie przenieść te funkcje z dialogu do innego skryptu, zostawiam do pokminienia, w każdym razie musi też być uodpornienei na to co pisałem w pierwszej części
> 
> zmieniłam kolejność wypełniania dialogu - robi się to w funkcji _run_ zamiast przy inicjalizacji to rozwiązuje problem o którym wspomniałeś btw jakbyś mergował to proszę zesquoshuj commity

O Mega! To zrobię to jakoś koło 14/15

2024-05-11 11:52 UTC, wojtek19022 approved these changes
Świetnie!

2024-05-11 12:26 UTC, wojtek19022 commented
Coś jednak tutaj się nie zgadza, bo nie przeniosłaś tej funkcjonalności z dialogu do runa. Dokończę to i wypchnę zmiany

2024-05-11 12:27 UTC, wojtek19022 requested changes
Dorobię zmianę działania tej funkcjonalności, ponieważ dziwnie działają te wyszarzania i wygaszania przez ostatnie zmiany

2024-05-11 18:40 UTC, merged